# Generated by Django 3.0.4 on 2020-04-28 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cell',
            table='cell',
        ),
        migrations.AlterModelTable(
            name='device',
            table='device',
        ),
    ]
