# Generated by Django 3.0.4 on 2020-04-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200428_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='record_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='record_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='smartne',
            name='record_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='smartsite',
            name='record_status',
            field=models.IntegerField(default=1),
        ),
    ]
