# Generated by Django 3.2.5 on 2021-08-04 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ems_trx_id', models.CharField(blank=True, max_length=140, null=True)),
                ('ems_id', models.CharField(blank=True, max_length=15, null=True)),
                ('trx_name', models.CharField(blank=True, max_length=140, null=True)),
                ('dn', models.CharField(blank=True, max_length=140, null=True)),
                ('site_id', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_dn', models.CharField(blank=True, max_length=140, null=True)),
                ('admin_state', models.CharField(blank=True, max_length=15, null=True)),
                ('e1_assignment', models.CharField(blank=True, max_length=10, null=True)),
                ('homing_bts', models.CharField(blank=True, max_length=20, null=True)),
                ('record_status', models.IntegerField(default=1)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cell')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
            options={
                'verbose_name_plural': 'TRX',
                'db_table': 'Trx',
            },
        ),
        migrations.DeleteModel(
            name='LR_TRX',
        ),
    ]
