# Generated by Django 3.0.4 on 2020-05-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200429_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartParkedNe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_parked', models.DateTimeField()),
                ('record_status', models.IntegerField(default=1)),
                ('update_at', models.DateTimeField()),
                ('sitene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SmartNe')),
            ],
            options={
                'db_table': 'smart_parked_ne',
            },
        ),
    ]
