# Generated by Django 3.0.4 on 2020-06-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200616_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSyncStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=250)),
                ('ne_type', models.CharField(max_length=50)),
                ('sync_status', models.CharField(max_length=25)),
                ('record_status', models.IntegerField(default=1)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_sync_status',
            },
        ),
    ]
