# Generated by Django 3.0.4 on 2020-06-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_devicesyncstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesyncstatus',
            name='device_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
