# Generated by Django 3.2.5 on 2021-09-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmsdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RAN_Cell',
            new_name='Cell',
        ),
    ]
