# Generated by Django 3.2.5 on 2021-09-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmsdata', '0003_auto_20210901_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='lcr_id',
            new_name='lcr_cid',
        ),
    ]
