# Generated by Django 3.2.5 on 2021-07-30 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField()),
                ('tech', models.CharField(max_length=250)),
                ('counterpart', models.CharField(blank=True, max_length=250, null=True)),
                ('rfs_count', models.IntegerField(blank=True, null=True)),
                ('band', models.CharField(blank=True, max_length=250, null=True)),
                ('vendor', models.CharField(blank=True, max_length=250, null=True)),
                ('homing', models.CharField(blank=True, max_length=250, null=True)),
                ('bts_id', models.CharField(blank=True, max_length=250, null=True)),
                ('device_name', models.CharField(blank=True, max_length=250, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=250, null=True)),
                ('trx_config', models.CharField(blank=True, max_length=250, null=True)),
                ('iub_type', models.CharField(blank=True, max_length=250, null=True)),
                ('bandwidth', models.IntegerField(blank=True, null=True)),
                ('sac', models.CharField(blank=True, max_length=250, null=True)),
                ('cell_id', models.CharField(blank=True, max_length=250, null=True)),
                ('cell_name', models.CharField(blank=True, max_length=250, null=True)),
                ('lac', models.CharField(blank=True, max_length=250, null=True)),
                ('pci', models.CharField(blank=True, max_length=250, null=True)),
                ('omip', models.CharField(blank=True, max_length=250, null=True)),
                ('s1_c', models.CharField(blank=True, max_length=250, null=True)),
                ('s1_u', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edrar.activity')),
            ],
        ),
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivityModified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(blank=True, max_length=250, null=True)),
                ('old_value', models.CharField(blank=True, max_length=250, null=True)),
                ('new_value', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity_SmartSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('create_flag', models.IntegerField(blank=True, null=True)),
                ('update_flag', models.BooleanField()),
                ('daily_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edrar.dailyactivity')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.smartsite')),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity_Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('create_flag', models.IntegerField(blank=True, null=True)),
                ('update_flag', models.BooleanField()),
                ('daily_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edrar.dailyactivity')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivity_Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('create_flag', models.IntegerField(blank=True, null=True)),
                ('update_flag', models.BooleanField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cell')),
                ('daily_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edrar.dailyactivity')),
            ],
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='modified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edrar.dailyactivitymodified'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='site_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edrar.sitestatus'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='siteid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.smartsite'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
