# Generated by Django 3.2.5 on 2021-08-04 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210804_1405'),
        ('edrar', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity_Trx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('create_flag', models.IntegerField(blank=True, null=True)),
                ('update_flag', models.BooleanField()),
                ('daily_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edrar.dailyactivity')),
                ('trx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trx')),
            ],
        ),
    ]
