# Generated by Django 3.2.5 on 2021-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrar', '0004_mobiletechnology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobiletechnology',
            options={'verbose_name_plural': 'Mobile Technologies'},
        ),
        migrations.AddField(
            model_name='mobiletechnology',
            name='alias',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
