# Generated by Django 3.2.5 on 2021-08-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrar', '0005_auto_20210819_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileFrequencyBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.IntegerField()),
                ('alias', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Mobile Technologies',
            },
        ),
    ]
