# Generated by Django 3.2.5 on 2021-08-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edrar', '0006_mobilefrequencyband'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilefrequencyband',
            options={'verbose_name_plural': 'Mobile Freq Bands'},
        ),
    ]
