# Generated by Django 3.2.5 on 2021-08-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edrar', '0007_alter_mobilefrequencyband_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilefrequencyband',
            name='alias',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mobiletechnology',
            name='alias',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
