# Generated by Django 3.2.5 on 2021-08-31 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edrar', '0008_auto_20210819_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='modified',
        ),
        migrations.AddField(
            model_name='dailyactivitymodified',
            name='activity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edrar.dailyactivity'),
            preserve_default=False,
        ),
    ]
